//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public string Employee { get; set; }
        public int CustomerID { get; set; }
        public int BillID { get; set; }
        public int Paid { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> ChequeID { get; set; }
    
        public virtual cheque cheque { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
